services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: jakserSaas
      POSTGRES_USER: jakser
      POSTGRES_PASSWORD: qwerty123
    ports:
      - 5432:5432 # make sure you don't have another container running on DB_PORT
    volumes:
      - ./data/db:/var/lib/postgresql/data
    attach: false

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
